pipeline:
  name: 'default'
  page_classifier:
    - model_name_or_path: 'marie/lmv3-medical-document-classification'
      type: 'transformers'
      task: 'text-classification-multimodal'
      device: 'cuda'
      enabled: True
      name: 'medical-page-classifier'
      group: 'medical_page_classifier'

    - model_name_or_path: 'marie/lmv3-medical-document-payer'
      type: 'transformers'
      enabled: False
      device: 'cuda'
      name: 'medical_payer_classifier'
  page_indexer:
    - model_name_or_path: 'rms/layoutlmv3-large-patpay-ner'
      enabled: False
      type: 'transformers'
      device: 'cuda'
      name: 'page_indexer_patient'
      filter:
        type: 'regex'
        pattern: '.*'

  page_boundary:
    model_name_or_path: 'rms/page-boundary-detection'
    device: 'cuda'
    name: 'page_boundary_default'
    filter:
      type: 'regex'
      pattern: '.*'

  page_splitter:
    model_name_or_path: 'marie/layoutlmv3-medical-document-splitter'
    enabled: True