pipeline:
  name: 'default-corr'
  page_classifier:
    - model_name_or_path: 'rms/corr-layoutlmv3-classifier'
      name: 'corr_page_layoutlmv3_classifier'
      type: 'transformers'
      task: 'text-classification-multimodal'
      device: 'cuda'
      enabled: True
      # specific options for LayoutLMv3
#      feature_extractor: LayoutLMv3ImageProcessor,
#      image_processor: LayoutLMv3Processor

#    - model_name_or_path: 'rms/corr-longformer-classifier'
#      task: 'text-classification'
#      name: 'corr_page_longformer_classifier'
#      type: 'transformers'
#      enabled: True
#      device: 'cuda'

  sub_classifier:
    - model_name_or_path: 'rms/layoutlmv3-large-patpay-ner'
      enabled: True
      type: 'transformers'
      device: 'cuda'
      name: 'subclassifier_corr_auth'
      filter:
        type: 'regex'
        pattern: '.*'