---
- name: Marie-AI cluster
  hosts: ml_cluster
  become_user: gpu-svc
  
  tasks:
  - name: User Info
    shell: whoami
    register: out
  - debug: var=out.stdout_lines


  # check if docker conttainer is running given the container name

  # Check if Docker is installed
  - name: Check if Docker is installed
    command: docker --version
    register: docker_version
    failed_when: docker_version.rc != 0
    changed_when: false
