base:
  model_executors:
    qwen_v2_5_vl: executor_qwen_v2_5_vl_default
    qwen_v2_5: executor_qwen_v2_5_default
  serverless_executor: serverless_executor_default

12345:
  model_executors:
    qwen_v2_5_vl: executor_qwen_v2_5_vl
    qwen_v2_5: executor_qwen_v2_5
