################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: false

################################################################
# Ping configuration
################################################################
# Enable ping
ping:
  entryPoint: traefik

################################################################
# Access logs configuration
################################################################
# Enable access logs
accessLog:
  filePath: /etc/traefik/log/access.log
  format: json

log:
  level: DEBUG
  filePath: /etc/traefik/log/traefik.log
  format: json

api:
  dashboard: true
  insecure: false
  debug: false


metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0


entryPoints:
  traefik:
    address: ":7777"
  marie:
    address: ":5000"

providers:
  providersThrottleDuration: 2s
  file:
    filename: /etc/traefik/file-provider.yml
    watch: true
    debugLogGeneratedTemplate: true
#
#  docker:
#    exposedByDefault: false
#    watch: true
#
#  consulcatalog:
#    connectAware: false
#    exposedByDefault: true
#    connectByDefault: true
#    cache: false
#    prefix: traefik
#    servicename: traefik-system-ingress
#    endpoint:
#      datacenter: "dc1"
#      address: "http://localhost:8500"

